### ISSUE TITLE
Unable to install on OSX 10.11.5

### ISSUE THREAD

**Issue by eduardocoelho** [kewitz/git-semantics#4]
When I run `install.sh` I get the following output:

```
Eduardos-MacBook-Air:git-semantics eduardocoelho$ ./install.sh 

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

Copying file...
Password:
cp: /usr/share/git-core/templates/hooks: No such file or directory
Done!
```

I was able to get it running by performing a manual installation though (moving `commit-msg` to `.git/hooks` on some repositories).

---

INFO:
- OSX 10.11.5 (15F34)
- git version 2.7.4 (Apple Git-66)

**Comment by kewitz** [comment]
Hey @eduardocoelho!

By default on Ubuntu we already have the locate index service running by default. I don't know how that works on OSX tho.
Apparently, if you want to, you can start this service by running `sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist`

Also, you can now install this in a specific repository running `./install.sh path/to/repo`.

Thanks! :grin:
